### ISSUE TITLE
Fix cucumber tests and add new ones

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#151]
Add cucumber tests, make sure they work. Puppeteer should also to be able to automatically test interface functionalities (?).

**Comment by nicomencia** [comment]
The biggest problem we are facing with cucumber+puppeteer at this moment is that it cannot find the called adress of the program due to the routing. I propose two things:

- Fix the tests in some way to access the correct adress even with the routing

- Run the test vs the app deployed in github pages
