### ISSUE TITLE
Bug: Codacy not able to access branches

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#25]
Hello there,

After merging two branches with part of the documentation, Codacy reported an error saying that it wasn't able to reach GitHub to see the branch and run its tests. If you follow the help given by the error, it asks you for more permissions to your GitHub account from their website. 

I didn't find this correct so I want to ask whether you know what might be happening... Maybe we introduced something wrong into the documentation *.adoc files. We are kind of lost. Could you help us?

@labra, @pglez82

**Comment by fincamd** [comment]
Obviously, if you all guys know about a solution to this problem, it will be more than welcome. : )
@Drastur @oscar134 @nicomencia @jesQM

**Comment by pglez82** [comment]
I do not think thats an error. Codacy is only telling that it is configured to analyse only the master branch, so the development branch is not analysed. This can be configured in the codacy dashboard. Maybe the problem is that you do not have enough permissions to do this in codacy? As far as I know, if you have read/write permission over a repository (and you have it) you should be able to change the codacy configuration for the repository. Let me know if it helps.

**Comment by fincamd** [comment]
Oh I will try to modify that so it also considers development at least.

Thanks!

**Comment by fincamd** [comment]
Okey, after checking the dashboard I am afraid I don't have permissions to modify codacy build/check settings. Maybe I don't know how to do it. I'm lost

**Comment by pglez82** [comment]
It seems to be a problem with permissions. You should be able to see a settings button in the Codacy page (left column at the bottom). There you change the branches that are analysed. If you do not see this option there should be a problem with the permissions that we have to investigate. I will change the setting to remove this warning.

**Comment by fincamd** [comment]
It seems that now Codacy also scans development branch. Thanks if you did that.

By the way I'm not able to see any kind of settings button on the left column.
